on:
  schedule:
    - cron: "17 * * * *"
  push:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://git.openembedded.org/meta-python2"
          source_branch: "*"
          destination_repo: "HalleyAssist/meta-python2"
          destination_branch: "*"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}